Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -19,13 +19,17 @@ jobs:
       - name: build
         run: msbuild numpadEmu.sln /p:Configuration=Release
 
-      - name: Find Executable
+      - name: find
         id: find_executable
         run: |
-          echo "searching the exe..."
-          exe_path=$(find ${{ github.workspace }} -name "numpadEmu.exe" -print -quit)
-          echo "found at: $exe_path"
-          echo "::set-output name=exe_path::$exe_path"
+          $exe_path = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter "numpadEmu.exe" | Select-Object -First 1
+          if ($exe_path) {
+            echo "exe found at: $exe_path"
+            echo "::set-output name=exe_path::$($exe_path.FullName)"
+          } else {
+            echo "exe not found."
+            exit 1
+          }
 
       - name: release
         id: create_release
